```{r}
#install.packages("purrr")
```

```{r}
library(purrr)
library(readxl)
library(tidyverse)
library(stringr)
library(car)

k.aps <- read.csv("../Data/kaggle_aps/train.csv", header = T, stringsAsFactors = F, row.names = "X")


```
```{r}
# Simple Preview

head(k.aps, 10)
```
```{r}
# Basic Summary of the columns

summary(k.aps)
```
```{r}
# A different column summary, shows a preview of values. 
str(k.aps)
```


```{r}
# For character fields, collect all of the possible values and display them. 
# I found this on a stack overflow post, don't entirely understand it. 

k.aps %>% select(where(is.character) )%>% 
    map(~str_c(unique(.x),collapse = ",")) %>% 
    bind_rows() %>% 
    gather(key = col_name, value = col_unique)
    

```
```{r}

# convert independent variables to factors
# convert dependent variable to 1/0 value
# drop the id column

k.aps.clean = k.aps %>% mutate(Gender=factor(Gender),
                         Customer.Type=factor(Customer.Type),
                         Type.of.Travel=factor(Type.of.Travel),
                         Class=factor(Class),
                         satisfaction=ifelse(satisfaction=="satisfied", 1,0)) %>% 
                  select(!id)
# preview it
head(k.aps.clean)

```
```{r}
m <- glm(satisfaction~ .^2, "binomial", k.aps.clean)
summary(m)
```


```{r}
# train.n is equal to the record count of a 70% segment of the data
train.n <- (round(0.7 * length(k.aps.clean$Gender)))

# generate row indices randomly
indices <- sample(seq(1, length(k.aps.clean$Gender
                                )), train.n)

# use the row indices to populate a training set
train <- k.aps.clean[indices,]
# reverse the row indices to populate a validation set
validate <-k.aps.clean[-indices,]
head(train)
head(validate)


```
```{r}
# retrain the model using only the training set
m <- (glm(satisfaction~., "binomial", train))
summary(m)
```



```{r}
# make predictions of the "response" type (probabilities)
# round those probabilities to create 0/1 predictions

validate["prediction"] <- round(predict(m, validate, type="response"))

# take the average of a boolean comparison to get accuracy
mean(validate["satisfaction"]==validate["prediction"], na.rm = T)

```



